// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3 = "CgkI5J6ApJYVEAIQAw"; // <GPGSID>
        public const string achievement_4 = "CgkI5J6ApJYVEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkI5J6ApJYVEAIQBQ"; // <GPGSID>
        public const string achievement_6 = "CgkI5J6ApJYVEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkI5J6ApJYVEAIQCA"; // <GPGSID>
        public const string achievement_8 = "CgkI5J6ApJYVEAIQBg"; // <GPGSID>
        public const string achievement_9 = "CgkI5J6ApJYVEAIQCQ"; // <GPGSID>
        public const string achievement_16 = "CgkI5J6ApJYVEAIQEg"; // <GPGSID>
        public const string achievement_17 = "CgkI5J6ApJYVEAIQEw"; // <GPGSID>
        public const string leaderboard = "CgkI5J6ApJYVEAIQFA"; // <GPGSID>
        public const string achievement_10 = "CgkI5J6ApJYVEAIQFg"; // <GPGSID>
        public const string achievement_11 = "CgkI5J6ApJYVEAIQCg"; // <GPGSID>
        public const string achievement_12 = "CgkI5J6ApJYVEAIQCw"; // <GPGSID>
        public const string achievement_13 = "CgkI5J6ApJYVEAIQDA"; // <GPGSID>
        public const string achievement_14 = "CgkI5J6ApJYVEAIQDQ"; // <GPGSID>
        public const string achievement_15 = "CgkI5J6ApJYVEAIQDg"; // <GPGSID>
        public const string achievement__100 = "CgkI5J6ApJYVEAIQEA"; // <GPGSID>
        public const string leaderboard_2 = "CgkI5J6ApJYVEAIQFQ"; // <GPGSID>
        public const string achievement__10 = "CgkI5J6ApJYVEAIQDw"; // <GPGSID>
        public const string achievement_swat = "CgkI5J6ApJYVEAIQEQ"; // <GPGSID>
        public const string achievement = "CgkI5J6ApJYVEAIQAQ"; // <GPGSID>
        public const string achievement_2 = "CgkI5J6ApJYVEAIQAg"; // <GPGSID>

}

